server:
  port: 5006
spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb?createDatabaseIfNotExist=true
    username: root
    password: Tirth@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa.show-sql: true

razorpay:
    api:
      key: "your razorpay api key"
      secret: "your razorpay api secret"
  
stripe:
  api:
    key: "your stripe api key"
    secret: "your stripe api secret"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/